services:
  - type: web
    name: mansao-das-sombras-websocket
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
